### ISSUE TITLE
cosmic_ray exec does nothing

### ISSUE THREAD

**Issue by snarfed** [sixty-north/cosmic-ray#365]
hi all! i've been excited to try cosmic ray for a long time, and i've finally ported the packages i have in mind to python 3. can't wait!

i tried it out just now, 3.1.2 on python 3.6.4. i ran `cosmic-ray init cosmic-ray.yml cosmic-ray`, and it died since `cosmic-ray.yml`, so i wrote one myself:

```yaml
module: granary

baseline: 10

exclude-modules: granary.test.test_atom

test-runner:
  name: unittest
  args: granary/test/

execution-engine:
  name: local
```

i ran `cosmic-ray init cosmic-ray.yml cosmic-ray` again, and it ran ok and generated this `cosmic-ray.json`:

```json
{
  "_default": null,
  "config": {
    "1": {
      "config": {
        "baseline": 10,
        "exclude-modules": "granary.test.test_atom",
        "execution-engine": {
          "name": "local"
        },
        "module": "granary",
        "test-runner": {
          "args": "granary/test/",
          "name": "unittest"
        }
      },
      "timeout": 32.44012
    }
  },
  "work-items": null
}
```

i then ran `cosmic-ray exec cosmic-ray`, and it exited immediately with status code 0. any idea what happened? `"work-items": null` in the json looks suspicious to me...should it have something instead of null?

in case it helps, here are the CI builds for granary: https://circleci.com/gh/snarfed/granary

thanks in advance!
